// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAUCLplRFIT4siCk6_O_uj8imSXTe3Na2o',
    appId: '1:372231939394:web:a1c4435a9a667b30fad4db',
    messagingSenderId: '372231939394',
    projectId: 'hrms-a4a85',
    authDomain: 'hrms-a4a85.firebaseapp.com',
    storageBucket: 'hrms-a4a85.firebasestorage.app',
    measurementId: 'G-MMX69096NN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAz1MBrMYYbBzBC742UuYvaDs9ookkyX0k',
    appId: '1:372231939394:android:7ccda269fb2e3169fad4db',
    messagingSenderId: '372231939394',
    projectId: 'hrms-a4a85',
    storageBucket: 'hrms-a4a85.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDVtQixTezi3DLuxs6e30q_-jSK7Js99oo',
    appId: '1:372231939394:ios:0000e975931e04e2fad4db',
    messagingSenderId: '372231939394',
    projectId: 'hrms-a4a85',
    storageBucket: 'hrms-a4a85.firebasestorage.app',
    iosBundleId: 'com.hcphrms.hcpHrms',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDVtQixTezi3DLuxs6e30q_-jSK7Js99oo',
    appId: '1:372231939394:ios:0000e975931e04e2fad4db',
    messagingSenderId: '372231939394',
    projectId: 'hrms-a4a85',
    storageBucket: 'hrms-a4a85.firebasestorage.app',
    iosBundleId: 'com.hcphrms.hcpHrms',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAUCLplRFIT4siCk6_O_uj8imSXTe3Na2o',
    appId: '1:372231939394:web:8dc6e990e906e7e2fad4db',
    messagingSenderId: '372231939394',
    projectId: 'hrms-a4a85',
    authDomain: 'hrms-a4a85.firebaseapp.com',
    storageBucket: 'hrms-a4a85.firebasestorage.app',
    measurementId: 'G-22EHSXJJFY',
  );
}
